### ISSUE TITLE
PID line follow with  MR Optical Distance Sensor

### ISSUE THREAD

**Issue by ram4robotics** [ftc-9773/ftc_app_9773_velocity_vortex#4]

**Comment by LukefromSTUBBY** [comment]
I see I have been "assigned," but I cannot see what I have been assigned. Am I supposed to write a line-follow program?

**Comment by ram4robotics** [comment]
Yes, I think line follow using the optical distance sensor will be a good first program for you, since you may have already done it in FLL.  To see the issue you are assigned,  you probably have to install "ZenHub" browser extension. Refer to my e-mail few minutes ago.
