### ISSUE TITLE
Investigate: Compare Vuforia and OpenCV for color detection

### ISSUE THREAD

**Issue by pranavburugula** [ftc-9773/ftc_app_9773_velocity_vortex#45]

**Comment by ram4robotics** [comment]
Hi Mike,  what is your conclusion about the usability of vuforia for color beacon detection ?
Thanks,
Ram

**Comment by michaela10c** [comment]
Vuforia is not very useful for color beacon detection, as it cannot detect the actual colors of an object, although it can track the position of the robot and the object. Even if Vuforia has some capabilities, OpenCV is much better at doing so than Vuforia. I had found very little or no evidence that color detection can be used in Vuforia, but lots of it in OpenCV. 




------------------ 原始邮件 ------------------
发件人: "ram4ftc";<notifications@github.com>;
发送时间: 2016年12月20日(星期二) 上午6:25
收件人: "ftc-9773/ftc_app_9773_velocity_vortex"<ftc_app_9773_velocity_vortex@noreply.github.com>; 
抄送: "Michael Zhou"<michaela10c@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [ftc-9773/ftc_app_9773_velocity_vortex] Investigate: CompareVuforia and OpenCV for color detection (#45)




Hi Mike,  what is your conclusion about the usability of vuforia for color beacon detection ?
 Thanks,
 Ram
